#
# Release pipeline. Run build and deploy for Platta staging and production environments.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  tags:
    include:
    - release-*
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: pysakoinnin-verkkokauppa-pipelines
    type: git
    # project/repository
    name: pysakoinnin-verkkokauppa/pysakoinnin-verkkokauppa-pipelines

extends:
  template: azure-pipelines-pysakoinninverkkokauppa-frontend-stgn-prod.yml@pysakoinnin-verkkokauppa-pipelines
