# File: parking-permits/azure-pipelines-release.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: pysakoinnin-verkkokauppa-pipelines
    type: git
    # project/repository
    name: pysakoinnin-verkkokauppa/pysakoinnin-verkkokauppa-pipelines

extends:
  template: azure-pipelines-pysakoinninverkkokauppa-frontend-stgn-prod.yml@pysakoinnin-verkkokauppa-pipelines
